import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Top } from "./components/top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className=" bg-color30 h-screen">
          <div
          className="animate-up-normal"
          >
            <Top />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
