"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/footer";
import { Top } from "../components/top";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div  className={` bg-color30`}>

      <div className="h-[15vh]">
        <Top/>
        </div>
        {children}
      <Footer/>
        </div>
      </body>
    </html>
  );
}
